#!/bin/sh

brew_tap 'caskroom/cask'
brew_install_or_upgrade 'brew-cask'

apps=(
  alfred
  appcleaner
  astah-community
  atom
  caffeine
  cyberduck
  disk-inventory-x
  dropbox
  evernote
  flux
  github-desktop
  google-drive
  iterm2
  imageoptim
  lastfm
  licecap
  macvim
  noizio
  pg-commander
  rowanj-gitx
  sequel-pro
  sizeup
  skype
  slack
  the-unarchiver
  transmission
  vlc
  xquartz
  xscope
  yate
)

homebrew_packages=(
  ffmpeg
  gcc
  ghostscript
  htop
  lame
  media-info
  mkvtoolnix
  phantomjs
  ssh-copy-id
  tig
  v8
  wget
  youtube-dl
)

fancy_echo "Installing apps"
for pkg in "${apps[@]}"
do
  brew cask install $pkg
done

fancy_echo "Installing homebrew packages"
for pkg in "${homebrew_packages[@]}"
do
  brew_install_or_upgrade $pkg
done
